on:
  push:
    branches:
      - main





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Printing folder content before'
        run: ls

      - uses: actions/checkout@v3

      - name: 'Printing folder content after'
        run: ls

      


        
